name: assets_scanner
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.5
  path: ^1.6.4

dev_dependencies:
  test: ^1.14.2
  build_test: ^0.10.12+1
