container:
  image: cirrusci/flutter:latest
  cpu: 8
  memory: 16G

check_task:
  flutter_doctor_script: flutter doctor -v
  flutter_analyze_script:
    - bash scripts/dartfmt_check.sh 
    - flutter packages get
    - cd example
    - flutter packages pub run build_runner build --delete-conflicting-outputs
    - cd ..
    - flutter analyze
    - dart run test