container:
  image: cirrusci/flutter:latest
  cpu: 8
  memory: 16G

check_task:
  flutter_doctor_script: flutter doctor -v
  flutter_analyze_script:
    - flutter packages get
    - flutter packages pub run build_runner build
    - flutter analyze
    - pub run test