container:
  image: cirrusci/flutter:latest
  cpu: 8
  memory: 16G

check_task:
  flutter_doctor_script: flutter doctor -v
  flutter_analyze_script:
    - cd assets_scanner
    - flutter packages get
    - flutter analyze
    - flutter test