name: assets_scanner
description: assets_scanner helps you generate assets path constants to r.dart file, you can preview the images assets by hovering over the constants.
version: 1.1.2
author: littleGnAl
homepage: https://github.com/littleGnAl/assets-scanner

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.5.0
  path: ^1.7.0
  glob: ^1.2.0
  yaml: ^2.2.1
  meta: ^1.2.3

dev_dependencies:
  test: ^1.15.5
  build_test: ^1.3.0
