name: assets_scanner
description: Assets Scanner helps you generate constants for assets, reducing the probability of misspellings. At the same time, you can hover over the constants to preview the images more intuitively.
version: 0.0.2
author: littleGnAl
homepage: https://github.com/littleGnAl/assets-scanner

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.5
  path: ^1.6.4
  glob: ^1.2.0
  analyzer: ^0.39.4

dev_dependencies:
  test: ^1.14.2
  build_test: ^0.10.12+1
