/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class R {
  static const package = "example";

  static const r_123_alarm = "assets/123-alarm.png";

  static const alarm_white = "assets/alarm_white.png";

  static const baseline_3d_rotation_white = "assets/baseline_3d_rotation_white.png";

  static const arrow_right_alt_white = "assets/arrow_right_alt_white.png";

// ignore_for_file:lines_longer_than_80_chars,constant_identifier_names
}
